site_name: tokaua's hideout
site_url: https://wiki.tokaua.lol
repo_name: hideout
repo_url: https://github.com/tokaualol/hideout
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  # logo: /assets/logo.png
  # favicon: /assets/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  icon:
    edit: material/pencil 
    view: material/eye

  features:
    - navigation.instant # Internal links will be intercepted and dispatched via XHR without fully reloading the page.
    - navigation.instant.prefetch # Will start to fetch a page once the user hovers over a link.
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.share
    - header.autohide
    - navigation.footer
    - content.action.view
    - content.code.copy

extra:
  generator: false
#   homepage: / 
#   alternate:
#     - name: English
#       link: /
#       lang: en
#     - name: Spanish
#       link: /es/
#       lang: es

extra_css:
  - /assets/styles.css

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: date
      fallback_to_build_date: true
      
  - git-committers:
      enabled: !ENV [CI, false]
      repository: tokaualol/hideout
      branch: main

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

nav:
  - About: index.md
  # - Hall of Fame: hoa.md

  - Security:
    - VPNs: security/vpns.md
    - Ad Blocking: security/adblock.md
    - Alternaives: security/alternatives.md
    - Encryption: security/encrypt.md

  - Software:
    - Tools: software/tools.md
    - Scripts: software/scripts.md
    - Extensions: software/extensions.md
    - Self Host: software/selfhost.md
    - Piracy: software/piracy.md

  - Media:
    - Websites: media/websites.md
    - Movies & TV: media/moviestv.md
    - Anime & Manga: media/animemanga.md
    - Art: media/art.md
    - Wallpapers: media/wallpapers.md
    - Creators: media/creators.md
    - Videos: media/videos.md

  - Guides:
    - Self Host: guides/selfhost.md
    - Other: guides/other.md

  - Gaming:
    - Emulation: gaming/emulation.md
    - Minecraft: gaming/minecraft.md
    - VALVE: gaming/valve.md
    - Celeste: gaming/celeste.md
    - Roblox: gaming/roblox.md
    - Fortnite: gaming/fortnite.md

  - LGBTQ+:
    - Transgender: lgbtq/trans.md

  - Fun:
    - Websites: fun/websites.md
    - Copypastas: fun/copypastas.md

  - Contributing: contributing.md
  - Credits: credits.md